// ========================================================
//  GALLERY APPLICATION — scripts.js
//  --------------------------------------------------------
//  Photography portfolio with an interactive zoomable grid.
//
//  Architecture:
//    PreloaderManager  — Canvas-based loading animation shown
//                        while initial thumbnails are fetched.
//    FashionGallery    — Main app class. Manages:
//                          • Grid layout & responsive sizing
//                          • GSAP Draggable pan / scroll-wheel zoom
//                          • Split-screen image viewer (thumb → full)
//                          • Category filtering & index overlay
//                          • Web Audio synth sound effects
//    initMobileMenu()  — Hamburger menu wiring (standalone).
//
//  Data flow:
//    gallery-config.js  →  GALLERY_CATEGORIES[]
//         ↓
//    FashionGallery.initImageData()  →  this.fashionImages[]
//         ↓
//    generateGridItems()  →  DOM <div.grid-item> with <img> (thumbs/)
//         ↓
//    enterZoomMode()  →  scaling overlay loads full/ in background
//
//  Image variants (generated by optimize-photos.ps1 / .sh):
//    photos/<cat>/          — originals (not served to browser)
//    photos/<cat>/thumbs/   — 640px long-edge, q80  (grid)
//    photos/<cat>/full/     — 1920px long-edge, q85 (zoom view)
//
//  Dependencies: GSAP 3 (core, Draggable, CustomEase, Flip)
// ========================================================

gsap.registerPlugin(Draggable, CustomEase, Flip);

function shuffleArray(arr) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/**
 * Animated canvas preloader displayed while initial thumbnails load.
 * Call complete() to fade out and remove.
 */
class PreloaderManager {
  constructor() {
    this.overlay = null;
    this.canvas = null;
    this.ctx = null;
    this.animationId = null;
    this.startTime = null;
    this.duration = 2000; // 2 seconds
    this.createLoadingScreen();
  }

  createLoadingScreen() {
    this.overlay = document.getElementById("preloader-overlay");
    this.overlay.style.cssText = `
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: #000;
      display: flex;
      justify-content: center;
      align-items: center;
      z-index: 100000;
    `;

    this.canvas = document.createElement("canvas");
    this.canvas.width = 300;
    this.canvas.height = 300;

    this.ctx = this.canvas.getContext("2d");
    this.overlay.appendChild(this.canvas);

    this.startAnimation();
  }

  startAnimation() {
    const centerX = this.canvas.width / 2;
    const centerY = this.canvas.height / 2;
    let time = 0;
    let lastTime = 0;

    const dotRings = [
      { radius: 20, count: 8 },
      { radius: 35, count: 12 },
      { radius: 50, count: 16 },
      { radius: 65, count: 20 },
      { radius: 80, count: 24 }
    ];

    // Pre-compute RGB values once (not every frame)
    const primaryRgb = [0x2C, 0x1B, 0x14]; // #2C1B14
    const accentRgb  = [0xA6, 0x4B, 0x23]; // #A64B23

    const animate = (timestamp) => {
      if (!this.startTime) this.startTime = timestamp;

      if (!lastTime) lastTime = timestamp;
      const deltaTime = timestamp - lastTime;
      lastTime = timestamp;
      time += deltaTime * 0.001;

      this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);

      // Draw center dot
      this.ctx.beginPath();
      this.ctx.arc(centerX, centerY, 3, 0, Math.PI * 2);
      this.ctx.fillStyle = `rgba(${primaryRgb[0]}, ${primaryRgb[1]}, ${primaryRgb[2]}, 0.9)`;
      this.ctx.fill();

      // Draw Line Pulse Wave animation
      dotRings.forEach((ring, ringIndex) => {
        for (let i = 0; i < ring.count; i++) {
          const angle = (i / ring.count) * Math.PI * 2;
          const radiusPulse = Math.sin(time * 2 - ringIndex * 0.4) * 3;
          const x = centerX + Math.cos(angle) * (ring.radius + radiusPulse);
          const y = centerY + Math.sin(angle) * (ring.radius + radiusPulse);

          const opacityWave =
            0.4 + Math.sin(time * 2 - ringIndex * 0.4 + i * 0.2) * 0.6;
          const isActive = Math.sin(time * 2 - ringIndex * 0.4 + i * 0.2) > 0.6;
          const rgb = isActive ? accentRgb : primaryRgb;

          // Draw line from center to point
          this.ctx.beginPath();
          this.ctx.moveTo(centerX, centerY);
          this.ctx.lineTo(x, y);
          this.ctx.lineWidth = 0.8;
          this.ctx.strokeStyle = `rgba(${rgb[0]}, ${rgb[1]}, ${rgb[2]}, ${opacityWave * (isActive ? 0.7 : 0.5)})`;
          this.ctx.stroke();

          // Draw dot at the end of the line
          this.ctx.beginPath();
          this.ctx.arc(x, y, 2.5, 0, Math.PI * 2);
          this.ctx.fillStyle = `rgba(${rgb[0]}, ${rgb[1]}, ${rgb[2]}, ${opacityWave})`;
          this.ctx.fill();
        }
      });

      // Keep looping — the animation plays until complete() is called externally
      this.animationId = requestAnimationFrame(animate);
    };

    this.animationId = requestAnimationFrame(animate);
  }

  complete(onComplete) {
    if (this.animationId) {
      cancelAnimationFrame(this.animationId);
    }

    if (this.overlay) {
      this.overlay.style.opacity = "0";
      this.overlay.style.transition = "opacity 0.8s ease";
      setTimeout(() => {
        this.overlay?.remove();
        if (onComplete) onComplete();
      }, 800);
    }
  }
}

/**
 * Main gallery application.
 *
 * Lifecycle:  new FashionGallery() → init() → playIntroAnimation()
 *
 * Key state:
 *   fashionImages[]   – active image paths (from config or placeholders)
 *   gridItems[]       – { element, img, row, col, baseX, baseY, imageUrl, index }
 *   zoomState         – tracks split-screen viewer (isActive, selectedItem, overlay)
 *   config            – grid dimensions, zoom level, gap
 *   activeCategory    – current category id ('all' | category slug)
 */
const CONSTANTS = {
  ZOOM:      { NORMAL: 0.5 },
  GRID:      { WIDTH: 400, HEIGHT: 300, WIDTH_MOBILE: 260, HEIGHT_MOBILE: 195 },
  BREAKPOINT_MOBILE: 768,
  SWIPE_THRESHOLD: 60,
};

class FashionGallery {
  constructor() {
    // DOM elements
    this.viewport = document.getElementById("viewport");
    this.canvasWrapper = document.getElementById("canvasWrapper");
    this.gridContainer = document.getElementById("gridContainer");
    this.splitScreenContainer = document.getElementById("splitScreenContainer");
    this.navPrev = document.getElementById("navPrev");
    this.navNext = document.getElementById("navNext");
    this.controlsContainer = document.getElementById("controlsContainer");
    this.vmBtns = [0, 1, 2].map(i => document.getElementById(`vmBtn${i}`));
    this._switchButtons = Array.from(document.querySelectorAll(".switch-button"));
    // Create custom eases
    this.customEase = CustomEase.create("smooth", ".87,0,.13,1");
    this.centerEase = CustomEase.create("center", ".25,.46,.45,.94");
    // Detect mobile
    this.isMobile = window.innerWidth <= CONSTANTS.BREAKPOINT_MOBILE || ('ontouchstart' in window && window.innerWidth <= 1024);
    // Configuration — grid adapts to aspect ratio
    this.config = {
      itemWidth: this.isMobile ? CONSTANTS.GRID.WIDTH_MOBILE : CONSTANTS.GRID.WIDTH,
      itemHeight: this.isMobile ? CONSTANTS.GRID.HEIGHT_MOBILE : CONSTANTS.GRID.HEIGHT,
      baseGap: this.isMobile ? 10 : 16,
      rows: 8, // will be set below
      cols: 12, // will be set below
      currentZoom: this.isMobile ? 0.4 : 0.5,
      currentGap: this.isMobile ? 20 : 32
    };
    this.setGridShape();
    // State
    this.zoomState = {
      isActive: false,
      isFullscreen: false,
      selectedItem: null,
      flipAnimation: null,
      scalingOverlay: null
    };
    this.viewMode = 1; // 0=split, 1=css-fullscreen, 2=native-fullscreen
    this.gridItems = [];
    this.gridDimensions = {};
    this.lastValidPosition = {
      x: 0,
      y: 0
    };
    this.draggable = null;
    this._isDragging = false;
    this._isAnimating = false;
    this._pinchJustEnded = false;
    this._pinchActive = false;
    this.viewportObserver = null;
    this.activeCategory = 'all';
    this.indexOpen = false;
    // Bound event handler references (so removeEventListener works)
    this._boundHandleSplitAreaClick = this.handleSplitAreaClick.bind(this);
    this._boundHandleZoomKeys = this.handleZoomKeys.bind(this);
    this._boundHandleFullscreenChange = this.handleFullscreenChange.bind(this);
    document.addEventListener("fullscreenchange", this._boundHandleFullscreenChange);
    // View mode picker buttons
    this.vmGroup = document.getElementById('vmGroup');
    this.vmGroup.style.setProperty('--vm-active', 1);
    this.vmBtns.forEach((btn, i) => {
      btn.onclick = () => this._setViewMode(i);
    });
    // Initialize image data
    this.initImageData();
  }

  setGridShape() {
    const n = this.fashionImages ? this.fashionImages.length : 24;
    const vw = window.innerWidth;
    const vh = window.innerHeight;
    // Use the same reference gap as calculateFitZoom so the geometry is consistent
    const gap   = this.calculateGapForZoom(1.0);
    const cellW = this.config.itemWidth  + gap;
    const cellH = this.config.itemHeight + gap;

    // Solve for rows so that the grid's pixel aspect ratio matches the viewport:
    //   (cols * cellW) / (rows * cellH) = vw / vh,  cols * rows ≈ n
    //   → rows = sqrt(n * vh * cellW / (vw * cellH))
    const rawRows = Math.sqrt(n * vh * cellW / (vw * cellH));

    // Try floor and ceil; pick whichever produces a grid AR closer to the viewport AR
    const targetAR = vw / vh;
    const candidates = [Math.max(2, Math.floor(rawRows)), Math.max(2, Math.ceil(rawRows))];
    let bestRows = candidates[0];
    let bestDiff = Infinity;
    for (const r of candidates) {
      const c = Math.ceil(n / r);
      const diff = Math.abs((c * cellW) / (r * cellH) - targetAR);
      if (diff < bestDiff) { bestDiff = diff; bestRows = r; }
    }
    this.config.rows = bestRows;
    this.config.cols = Math.ceil(n / bestRows);
  }
  _updateConfigForViewport() {
    this.isMobile = window.innerWidth <= CONSTANTS.BREAKPOINT_MOBILE ||
      ('ontouchstart' in window && window.innerWidth <= 1024);
    this.config.itemWidth  = this.isMobile ? CONSTANTS.GRID.WIDTH_MOBILE  : CONSTANTS.GRID.WIDTH;
    this.config.itemHeight = this.isMobile ? CONSTANTS.GRID.HEIGHT_MOBILE : CONSTANTS.GRID.HEIGHT;
    this.config.baseGap    = this.isMobile ? 10 : 16;
  }
  _handleResize() {
    if (this.zoomState.isActive || this._pinchActive) return;
    this._updateConfigForViewport();
    this.setGridShape();
    const fitZoom = this.calculateFitZoom();
    this.config.currentZoom = fitZoom;
    this.config.currentGap  = this.calculateGapForZoom(fitZoom);
    this.generateGridItems();
    this.gridItems.forEach(({ element }) => { gsap.set(element, { opacity: 1 }); });
    gsap.set(this.canvasWrapper, { scale: fitZoom });
    this.calculateGridDimensions(this.config.currentGap);
    const vw = window.innerWidth;
    const vh = window.innerHeight;
    const { scaledWidth, scaledHeight } = this.gridDimensions;
    const cx = (vw - scaledWidth) / 2;
    const cy = (vh - scaledHeight) / 2;
    gsap.set(this.canvasWrapper, { x: cx, y: cy });
    this.lastValidPosition.x = cx;
    this.lastValidPosition.y = cy;
    this._targetZoom = fitZoom;
    this._targetX = cx;
    this._targetY = cy;
    if (this._scrollZoomTween) { this._scrollZoomTween.kill(); this._scrollZoomTween = null; }
    clearTimeout(this._scrollZoomDebounce);
    this.initDraggable();
    this.setupViewportObserver();
    this.updatePercentageIndicator(fitZoom);
  }
  /** Collect all image paths from GALLERY_CATEGORIES into this.fashionImages. */
  initImageData() {
    // Placeholder images (fallback when categories have no photos)
    this.placeholderImages = [];
    for (let i = 1; i <= 14; i++) {
      this.placeholderImages.push(
        "https://assets.codepen.io/7558/orange-portrait_" + String(i).padStart(2, "0") + ".jpg"
      );
    }

    if (typeof GALLERY_CATEGORIES !== 'undefined') {
      const allImages = [];
      shuffleArray(GALLERY_CATEGORIES).forEach(cat => allImages.push(...cat.images));
      this.fashionImages = allImages.length > 0 ? allImages : this.placeholderImages;
    } else {
      this.fashionImages = this.placeholderImages;
    }
  }
  calculateGapForZoom(zoomLevel) {
    if (this.isMobile) {
      if (zoomLevel >= 1.0) return 10;
      else if (zoomLevel >= 0.5) return 20;
      else return 40;
    }
    if (zoomLevel >= 1.0) return 16;
    else if (zoomLevel >= 0.5) return 32;
    else return 64;
  }
  calculateGridDimensions(gap = this.config.currentGap) {
    const totalWidth = this.config.cols * (this.config.itemWidth + gap) - gap;
    const totalHeight = this.config.rows * (this.config.itemHeight + gap) - gap;
    this.gridDimensions = {
      width: totalWidth,
      height: totalHeight,
      scaledWidth: totalWidth * this.config.currentZoom,
      scaledHeight: totalHeight * this.config.currentZoom,
      gap: gap
    };
    return this.gridDimensions;
  }
  generateGridItems() {
    this.config.currentGap = this.calculateGapForZoom(this.config.currentZoom);
    this.calculateGridDimensions();
    this.canvasWrapper.style.width = this.gridDimensions.width + "px";
    this.canvasWrapper.style.height = this.gridDimensions.height + "px";
    this.gridContainer.innerHTML = "";
    this.gridItems = [];

    let imageIndex = 0;
    for (let row = 0; row < this.config.rows; row++) {
      for (let col = 0; col < this.config.cols; col++) {
        const item = document.createElement("div");
        item.className = "grid-item";
        item.style.width = this.config.itemWidth + "px";
        item.style.height = this.config.itemHeight + "px";

        // Calculate final grid position
        const x = col * (this.config.itemWidth + this.config.currentGap);
        const y = row * (this.config.itemHeight + this.config.currentGap);

        // Set to grid position
        item.style.left = `${x}px`;
        item.style.top = `${y}px`;

        // Hide initially - will be positioned and shown in playIntroAnimation
        item.style.opacity = "0";

        const imageUrl = this.fashionImages[
          imageIndex % this.fashionImages.length
        ];
        imageIndex++;
        const img = document.createElement("img");
        img.src = this.toThumbPath(imageUrl);
        img.alt = `Fashion Portrait ${imageIndex}`;
        img.loading = "lazy";
        img.decoding = "async";
        img.addEventListener('load', () => img.classList.add('loaded'), { once: true });
        if (img.complete) img.classList.add('loaded');
        item.appendChild(img);
        const itemData = {
          element: item,
          img: img,
          row: row,
          col: col,
          baseX: x,
          baseY: y,
          imageUrl: imageUrl,
          index: this.gridItems.length
        };
        this.gridContainer.appendChild(item);
        this.gridItems.push(itemData);
      }
    }
  }
  setupViewportObserver() {
    if (this.viewportObserver) {
      this.viewportObserver.disconnect();
    }
    this.viewportObserver = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          // Skip if this is the currently selected item in zoom mode
          if (
            this.zoomState.selectedItem &&
            entry.target === this.zoomState.selectedItem.element
          ) {
            return;
          }
          // Use CSS transitions instead of per-item GSAP tweens for performance
          if (entry.isIntersecting) {
            entry.target.classList.remove("out-of-view");
          } else {
            entry.target.classList.add("out-of-view");
          }
        });
      },
      {
        root: null,
        threshold: 0.05,
        rootMargin: "20%"
      }
    );
    // Observe all grid items
    this.gridItems.forEach((item) => {
      this.viewportObserver.observe(item.element);
    });
  }
  // --- Path helpers for optimized images ---
  // Convert "photos/animals/01.jpg" → "photos/animals/thumbs/01.jpg"
  toThumbPath(url) {
    return url.replace(/\/([^/]+)$/, '/thumbs/$1');
  }
  // Convert any path (original or thumb) → "photos/animals/full/01.jpg"
  toFullPath(url) {
    // If it's already a full URL from the browser, extract the relative path
    try { url = new URL(url).pathname; } catch(e) { /* already relative */ }
    // Strip /thumbs/ or /full/ if present
    const clean = url.replace(/\/(thumbs|full)\//, '/');
    return clean.replace(/\/([^/]+)$/, '/full/$1');
  }

  createScalingOverlay(sourceImg) {
    const overlay = document.createElement("div");
    overlay.className = "scaling-image-overlay";
    const img = document.createElement("img");
    img.src = sourceImg.src;
    img.alt = sourceImg.alt;
    overlay.appendChild(img);
    document.body.appendChild(overlay);
    // Positioning is handled entirely by enterZoomMode — don't set it here
    // to avoid GSAP cache conflicts on sequential gsap.set calls.
    gsap.set(overlay, { opacity: 1 });
    // Load full-size in background and swap when ready
    const fullSrc = this.toFullPath(sourceImg.src);
    const pre = new Image();
    pre.onload = () => { img.src = fullSrc; };
    pre.src = fullSrc;
    return overlay;
  }
  /**
   * Returns the largest rect that fits `naturalWidth × naturalHeight` inside
   * `containerRect` while preserving aspect ratio (CSS object-fit: contain logic).
   */
  _containedRect(naturalWidth, naturalHeight, containerRect) {
    const imageAspect     = naturalWidth / naturalHeight;
    const containerAspect = containerRect.width / containerRect.height;
    const width  = imageAspect > containerAspect ? containerRect.width  : containerRect.height * imageAspect;
    const height = imageAspect > containerAspect ? containerRect.width  / imageAspect : containerRect.height;
    const left   = containerRect.left + (containerRect.width  - width)  / 2;
    const top    = containerRect.top  + (containerRect.height - height) / 2;
    return { width, height, left, top };
  }
  enterZoomMode(selectedItemData) {
    if (this.zoomState.isActive) return;
    this.zoomState.isActive = true;
    this.zoomState.selectedItem = selectedItemData;
    // Disable dragging
    if (this.draggable) this.draggable.disable();
    document.body.classList.add("zoom-mode");
    const splitContainer = this.splitScreenContainer;
    const zoomTarget = document.getElementById("zoomTarget");
    if (this.viewMode > 0) {
      // Apply fullscreen layout before reading rects — backdrop appears instantly, no split-screen flash
      this.zoomState.isFullscreen = true;
      document.body.classList.add("fullscreen-mode");
      splitContainer.classList.add("active");
      gsap.set(splitContainer, { opacity: 1 });
      if (this.viewMode === 2) {
        // Fire native fullscreen in parallel; if viewport changes on resolve,
        // _repositionOverlayToTarget kills the in-progress tween and corrects to the new target
        document.documentElement.requestFullscreen()
          .then(() => this._repositionOverlayToTarget())
          .catch(() => {});
      }
    } else {
      splitContainer.classList.add("active");
      gsap.to(splitContainer, { opacity: 1, duration: 0.4, ease: "expo.out" });
    }

    this.zoomState.scalingOverlay = this.createScalingOverlay(
      selectedItemData.img
    );
    this._preloadAdjacent(selectedItemData.index);
    gsap.set(selectedItemData.img, {
      opacity: 0
    });

    // Animate overlay from thumbnail position to zoom target using transforms (GPU-composited, no reflow)
    const overlay = this.zoomState.scalingOverlay;
    const cellRect  = selectedItemData.img.getBoundingClientRect();
    const targetRect = zoomTarget.getBoundingClientRect();

    // Derive natural dimensions (EXIF-corrected in modern browsers)
    const naturalWidth  = selectedItemData.img.naturalWidth  || cellRect.width;
    const naturalHeight = selectedItemData.img.naturalHeight || cellRect.height;

    // Contained image rect within zoom target (final overlay position)
    const target = this._containedRect(naturalWidth, naturalHeight, targetRect);

    // Contained image rect within grid cell — actual rendered content area to animate FROM.
    // Using the raw cellRect would distort portrait images (landscape cell ≠ portrait image rect).
    const source = this._containedRect(naturalWidth, naturalHeight, cellRect);

    // Set overlay to final size/position, use transforms to start from the source image content rect
    gsap.set(overlay, {
      left: target.left,
      top: target.top,
      width: target.width,
      height: target.height,
      transformOrigin: "top left",
      x: source.left - target.left,
      y: source.top  - target.top,
      scaleX: source.width  / target.width,
      scaleY: source.height / target.height,
    });

    // Animate only transforms — no layout thrashing
    this.zoomState.flipAnimation = gsap.to(overlay, {
      x: 0,
      y: 0,
      scaleX: 1,
      scaleY: 1,
      duration: 0.4,
      ease: "expo.out",
    });
    this.controlsContainer.classList.add("split-mode");
    // Check overlap after controls-container finishes transitioning to split position (1.2s)
    setTimeout(() => this._checkFooterOverlap(), 1250);
    // Show nav buttons
    this.navPrev.classList.add("active");
    this.navNext.classList.add("active");
    gsap.fromTo(this.navPrev, { y: 15, opacity: 0 }, { y: 0, opacity: 1, duration: 0.3, ease: "power2.out", delay: 0.35 });
    gsap.fromTo(this.navNext, { y: 15, opacity: 0 }, { y: 0, opacity: 1, duration: 0.3, ease: "power2.out", delay: 0.38 });
    // Wire nav button clicks
    this.navPrev.onclick = () => this.navigateZoom(-1);
    this.navNext.onclick = () => this.navigateZoom(1);
    // Add event listeners (use stored bound references so they can be removed)
    document
      .getElementById("splitLeft")
      .addEventListener("click", this._boundHandleSplitAreaClick);
    document
      .getElementById("splitRight")
      .addEventListener("click", this._boundHandleSplitAreaClick);
    document.addEventListener("keydown", this._boundHandleZoomKeys);
  }
  handleSplitAreaClick(e) {
    // Close when tapping empty space around the image, but not on
    // interactive elements (close button, nav buttons, title overlay)
    if (e.target.closest(".image-nav-btn")) return;
    if (e.target.closest(".fullscreen-btn")) return;
    this.exitZoomMode();
  }
  exitZoomMode() {
    if (
      !this.zoomState.isActive ||
      !this.zoomState.selectedItem ||
      !this.zoomState.scalingOverlay
    )
      return;
    document.removeEventListener("keydown", this._boundHandleZoomKeys);
    const splitLeft = document.getElementById("splitLeft");
    const splitRight = document.getElementById("splitRight");
    if (splitLeft)
      splitLeft.removeEventListener("click", this._boundHandleSplitAreaClick);
    if (splitRight)
      splitRight.removeEventListener("click", this._boundHandleSplitAreaClick);
    // Kill any pending/delayed tweens on the close button and nav buttons
    // to prevent the enterZoomMode animations (delayed) from re-showing them
    gsap.killTweensOf(this.navPrev);
    gsap.killTweensOf(this.navNext);
    const splitContainer = this.splitScreenContainer;
    const selectedElement = this.zoomState.selectedItem.element;
    const selectedImg = this.zoomState.selectedItem.img;
    if (this.zoomState.flipAnimation) {
      this.zoomState.flipAnimation.kill();
    }
    // Remove active class immediately so pointer-events are disabled
    // Hide nav buttons
    this.navPrev.classList.remove("active");
    this.navNext.classList.remove("active");
    gsap.to(this.navPrev, { opacity: 0, y: 15, duration: 0.3, ease: "power2.in" });
    gsap.to(this.navNext, { opacity: 0, y: 15, duration: 0.3, ease: "power2.in" });
    this.navPrev.onclick = null;
    this.navNext.onclick = null;
    // Track and clear fullscreen flag now, but keep the class until onComplete
    // so the layout stays in fullscreen-mode during the close animation (prevents ghost)
    const wasFullscreen = this.zoomState.isFullscreen;
    this.zoomState.isFullscreen = false;
    splitContainer.classList.remove("active");
    gsap.to(splitContainer, {
      opacity: 0,
      duration: 0.8,
      ease: "power2.out"
    });
    // Get the actual on-screen positions before clearing transforms
    const overlay = this.zoomState.scalingOverlay;
    const currentVisualRect = overlay.getBoundingClientRect();
    const thumbRect = selectedElement.getBoundingClientRect();

    // Compute the contained image rect within the cell (mirrors enterZoomMode source calc).
    // Using the raw thumbRect would distort images whose aspect ratio differs from the cell's.
    const naturalWidth  = selectedImg.naturalWidth  || thumbRect.width;
    const naturalHeight = selectedImg.naturalHeight || thumbRect.height;
    const source = this._containedRect(naturalWidth, naturalHeight, thumbRect);

    // Clear transforms to read the overlay's base layout position
    gsap.set(overlay, { clearProps: "x,y,scaleX,scaleY,scale" });
    const baseRect = overlay.getBoundingClientRect();

    // Restore current visual position using transforms (no layout change)
    gsap.set(overlay, {
      transformOrigin: "top left",
      x: currentVisualRect.left - baseRect.left,
      y: currentVisualRect.top  - baseRect.top,
      scaleX: currentVisualRect.width  / baseRect.width,
      scaleY: currentVisualRect.height / baseRect.height,
    });

    // Animate transforms to thumbnail position — no layout thrashing
    gsap.to(overlay, {
      x: source.left - baseRect.left,
      y: source.top  - baseRect.top,
      scaleX: source.width  / baseRect.width,
      scaleY: source.height / baseRect.height,
      duration: 0.4,
      ease: "expo.in",
      onComplete: () => {
        gsap.set(selectedImg, {
          opacity: 1
        });
        if (this.zoomState.scalingOverlay) {
          document.body.removeChild(this.zoomState.scalingOverlay);
          this.zoomState.scalingOverlay = null;
        }
        splitContainer.classList.remove("active");
        this.controlsContainer.classList.remove("split-mode");
        document.body.classList.remove("zoom-mode");
        if (wasFullscreen) {
          document.body.classList.remove("fullscreen-mode");
          // Only exit native fullscreen if not in native-fullscreen mode (viewMode 2)
          // so closing an image while in F11 keeps F11 active
          if (document.fullscreenElement && this.viewMode !== 2) {
            document.exitFullscreen().catch(() => {});
          }
        }
        if (this.draggable) this.draggable.enable();
        // Reset split-mode states
        const splitRight = document.getElementById('splitRight');
        if (splitRight) gsap.set(splitRight, { opacity: 1 });
        this.zoomState.isActive = false;
        this.zoomState.selectedItem = null;
        this.zoomState.flipAnimation = null;
        this._checkFooterOverlap();
      }
    });
  }
  _checkFooterOverlap() {
    const footerRight = document.querySelector('.footer-right');
    if (!footerRight || !this.vmGroup) return;
    const vmRect = this.vmGroup.getBoundingClientRect();
    const footerRect = footerRight.getBoundingClientRect();
    const overlaps = vmRect.left < footerRect.right + 8 &&
                     vmRect.right > footerRect.left - 8 &&
                     vmRect.top < footerRect.bottom + 8 &&
                     vmRect.bottom > footerRect.top - 8;
    document.body.classList.toggle('controls-overlap', overlaps);
  }
  handleZoomKeys(e) {
    if (!this.zoomState.isActive) return;
    if (e.key === "Escape") {
      if (this.zoomState.isFullscreen) {
        this.exitFullscreen();
      } else {
        this.exitZoomMode();
      }
    } else if (e.key === "ArrowRight") {
      e.preventDefault();
      this.navigateZoom(1);
    } else if (e.key === "ArrowLeft") {
      e.preventDefault();
      this.navigateZoom(-1);
    }
  }
  _setViewMode(mode) {
    const prev = this.viewMode;
    this.viewMode = mode;
    this.vmGroup.style.setProperty('--vm-active', mode);
    this.vmBtns.forEach((btn, i) => btn.classList.toggle('vm-active', i === mode));
    // Exit native fullscreen when switching away from mode 2, regardless of zoom state
    if (mode !== 2 && mode !== prev && document.fullscreenElement) {
      document.exitFullscreen().catch(() => {});
    }
    if (!this.zoomState.isActive) {
      if (mode === 2) {
        if (!document.fullscreenElement) {
          document.documentElement.requestFullscreen().catch(() => {});
        } else {
          document.exitFullscreen().catch(() => {});
        }
      }
      return;
    }
    if (mode === prev) return;
    if (mode === 0) {
      this.exitFullscreen();
    } else if (mode === 1) {
      if (!this.zoomState.isFullscreen) {
        this.enterFullscreen(false);
      } else if (document.fullscreenElement) {
        // Downgrade: exit native but keep CSS fullscreen
        document.exitFullscreen().catch(() => {});
        // handleFullscreenChange will reposition
      }
    } else if (mode === 2) {
      if (!this.zoomState.isFullscreen) {
        this.enterFullscreen(true);
      } else if (!document.fullscreenElement) {
        // Upgrade: add native on top of CSS fullscreen
        document.documentElement.requestFullscreen()
          .then(() => this._repositionOverlayToTarget())
          .catch(() => {});
      }
    }
  }
  enterFullscreen(useNative = true) {
    this.zoomState.isFullscreen = true;
    document.body.classList.add("fullscreen-mode");
    if (useNative) {
      document.documentElement.requestFullscreen()
        .then(() => this._repositionOverlayToTarget())
        .catch(() => this._repositionOverlayToTarget());
    } else {
      this._repositionOverlayToTarget();
    }
  }
  exitFullscreen() {
    if (!this.zoomState.isFullscreen) return;
    this.zoomState.isFullscreen = false;
    document.body.classList.remove("fullscreen-mode");
    if (document.fullscreenElement) {
      document.exitFullscreen().catch(() => {});
      // _repositionOverlayToTarget will be called by handleFullscreenChange
    } else {
      this._repositionOverlayToTarget();
    }
  }
  handleFullscreenChange() {
    if (!document.fullscreenElement && this.zoomState.isActive) {
      if (this.viewMode === 2) {
        // External native exit (Esc, F11, OS) — drop to CSS-only fullscreen
        this.viewMode = 1;
        this.vmGroup.style.setProperty('--vm-active', 1);
        this.vmBtns.forEach((btn, i) => btn.classList.toggle('vm-active', i === 1));
        // Keep fullscreen-mode class — still CSS fullscreen
      }
      this._repositionOverlayToTarget();
    }
  }
  _repositionOverlayToTarget() {
    const overlay = this.zoomState.scalingOverlay;
    if (!overlay) return;
    gsap.killTweensOf(overlay);
    const currentVisualRect = overlay.getBoundingClientRect();
    requestAnimationFrame(() => {
      const zoomTarget = document.getElementById('zoomTarget');
      const targetRect = zoomTarget.getBoundingClientRect();
      const img = overlay.querySelector('img');
      const naturalWidth  = img.naturalWidth  || targetRect.width;
      const naturalHeight = img.naturalHeight || targetRect.height;
      const contained = this._containedRect(naturalWidth, naturalHeight, targetRect);
      gsap.set(overlay, {
        left: contained.left,
        top: contained.top,
        width: contained.width,
        height: contained.height,
        transformOrigin: 'top left',
        x: currentVisualRect.left - contained.left,
        y: currentVisualRect.top  - contained.top,
        scaleX: currentVisualRect.width  / contained.width,
        scaleY: currentVisualRect.height / contained.height,
      });
      gsap.to(overlay, {
        x: 0, y: 0, scaleX: 1, scaleY: 1,
        duration: 0.4,
        ease: 'expo.out',
      });
    });
  }
  _preloadAdjacent(centerIndex) {
    const total = this.gridItems.length;
    if (this._adjacentPreloads) {
      this._adjacentPreloads.forEach(img => { img.src = ''; });
    }
    this._adjacentPreloads = [-1, 1, 2].map(offset => {
      const img = new Image();
      img.src = this.toFullPath(this.gridItems[(centerIndex + offset + total) % total].imageUrl);
      return img;
    });
  }
  navigateZoom(direction) {
    if (!this.zoomState.isActive || !this.zoomState.selectedItem) return;

    const overlay = this.zoomState.scalingOverlay;
    if (!overlay) return;

    // Kill any in-progress animation immediately — no blocking lock
    gsap.killTweensOf(overlay);
    if (this._navPreload)   { this._navPreload.onload = null; this._navPreload.src = ''; }
    if (this._thumbPreload) { this._thumbPreload.onload = null; this._thumbPreload.onerror = null; this._thumbPreload.src = ''; }

    // Update state immediately so rapid calls stay consistent
    const prevItem = this.zoomState.selectedItem;
    const totalItems = this.gridItems.length;
    const newIndex = (prevItem.index + direction + totalItems) % totalItems;
    const newItemData = this.gridItems[newIndex];
    this._preloadAdjacent(newIndex);

    gsap.set(prevItem.img, { opacity: 1 });
    gsap.set(newItemData.img, { opacity: 0 });
    this.zoomState.selectedItem = newItemData;

    const img = overlay.querySelector('img');
    const thumbSrc = this.toThumbPath(newItemData.imageUrl);
    const fullSrc  = this.toFullPath(newItemData.imageUrl);

    // Token cancels stale preload callbacks from superseded navigations
    if (!this._navToken) this._navToken = 0;
    const token = ++this._navToken;

    // Fast fade out → preload thumb → fade in
    gsap.to(overlay, {
      opacity: 0,
      duration: 0.08,
      ease: 'none',
      onComplete: () => {
        if (this._navToken !== token) return;

        const thumbPre = new Image();
        this._thumbPreload = thumbPre;

        const show = () => {
          if (this._navToken !== token) return;

          // Resize overlay to match new image's contained area while it's invisible.
          // Without this, a portrait image keeps the previous landscape overlay and the
          // border frames empty space.
          const zoomTarget = document.getElementById('zoomTarget');
          const targetRect    = zoomTarget.getBoundingClientRect();
          const naturalWidth  = thumbPre.naturalWidth  || targetRect.width;
          const naturalHeight = thumbPre.naturalHeight || targetRect.height;
          const contained = this._containedRect(naturalWidth, naturalHeight, targetRect);
          gsap.set(overlay, { left: contained.left, top: contained.top, width: contained.width, height: contained.height, x: 0, y: 0 });

          img.src = thumbSrc;
          gsap.fromTo(overlay, { opacity: 0 }, { opacity: 1, duration: 0.12, ease: 'none' });
          // Upgrade to full-res in background; decode() off main thread before swapping in
          const pre = new Image();
          this._navPreload = pre;
          pre.src = fullSrc;
          pre.decode().then(() => { if (this._navToken === token) img.src = fullSrc; }).catch(() => {});
        };

        thumbPre.onload  = show;
        thumbPre.onerror = show;
        thumbPre.src     = thumbSrc;
        if (thumbPre.complete) show();
      }
    });
  }


  initZoomSwipe() {
    const container = this.splitScreenContainer;
    const THRESHOLD = CONSTANTS.SWIPE_THRESHOLD;
    let startX = 0;
    let startY = 0;
    let tracking = false; // true once we've confirmed horizontal intent

    container.addEventListener('touchstart', (e) => {
      if (!this.zoomState.isActive || e.touches.length !== 1) return;
      startX = e.touches[0].clientX;
      startY = e.touches[0].clientY;
      tracking = false;
      // stop any spring-back in progress
      if (this.zoomState.scalingOverlay) {
        gsap.killTweensOf(this.zoomState.scalingOverlay);
        gsap.set(this.zoomState.scalingOverlay, { x: 0, opacity: 1 });
      }
    }, { passive: true });

    container.addEventListener('touchmove', (e) => {
      if (!this.zoomState.isActive || !this.zoomState.scalingOverlay || e.touches.length !== 1) return;
      const dx = e.touches[0].clientX - startX;
      const dy = e.touches[0].clientY - startY;

      // lock to vertical scroll if that's clearly the intent
      if (!tracking && Math.abs(dy) > Math.abs(dx)) return;
      tracking = true;
      e.preventDefault();

      const progress = Math.min(Math.abs(dx) / THRESHOLD, 1);
      gsap.set(this.zoomState.scalingOverlay, {
        x: dx * 0.65,
        opacity: 1 - progress * 0.25,
      });
    }, { passive: false });

    container.addEventListener('touchend', (e) => {
      if (!this.zoomState.isActive || !this.zoomState.scalingOverlay || !tracking) return;
      tracking = false;
      const dx = (e.changedTouches[0]?.clientX ?? startX) - startX;

      if (Math.abs(dx) >= THRESHOLD) {
        this.navigateZoom(dx < 0 ? 1 : -1);
      } else {
        // not enough — spring back
        gsap.to(this.zoomState.scalingOverlay, {
          x: 0, opacity: 1,
          duration: 0.45,
          ease: 'back.out(2)',
        });
      }
    }, { passive: true });
  }

  // --- Category Index ---
  buildCategoryIndex() {
    const list = document.getElementById('categoryList');
    if (!list || typeof GALLERY_CATEGORIES === 'undefined') return;
    list.innerHTML = '';

    // "All Work" row
    const allRow = document.createElement('div');
    allRow.className = 'category-row category-row-active';
    allRow.dataset.category = 'all';
    const totalPhotos = GALLERY_CATEGORIES.reduce((s, c) => s + c.images.length, 0);
    allRow.innerHTML = `
      <span class="category-number">✦</span>
      <span class="category-name">✦ ${window.t ? window.t('allWork') : 'All Work'}</span>

      <span class="category-count">${totalPhotos > 0 ? totalPhotos : '—'}</span>
    `;
    allRow.addEventListener('mouseenter', () => { this.updateCategoryPreview('all', 'All'); });
    allRow.addEventListener('click', () => { this.switchCategory('all'); this.closeCategoryIndex(); });
    list.appendChild(allRow);

    GALLERY_CATEGORIES.forEach((cat, i) => {
      const row = document.createElement('div');
      row.className = 'category-row';
      row.dataset.category = cat.id;
      const num = String(i + 1).padStart(2, '0');
      row.innerHTML = `
        <span class="category-number">${num}</span>
        <span class="category-name">${window.currentLang === 'ro' && cat.labelRo ? cat.labelRo : cat.label}</span>

        <span class="category-count">${cat.images.length > 0 ? cat.images.length : '—'}</span>
      `;
      const catDisplayLabel = window.currentLang === 'ro' && cat.labelRo ? cat.labelRo : cat.label;
      row.addEventListener('mouseenter', () => { this.updateCategoryPreview(cat.id, catDisplayLabel); });
      row.addEventListener('click', () => { this.switchCategory(cat.id); this.closeCategoryIndex(); });
      list.appendChild(row);
    });

    const updateFade = () => {
      const atTop = list.scrollTop <= 4;
      const atBottom = list.scrollHeight - list.scrollTop <= list.clientHeight + 4;
      list.classList.toggle('at-top', atTop);
      list.classList.toggle('at-bottom', atBottom);
    };
    list.addEventListener('scroll', updateFade, { passive: true });
    updateFade();
  }
  updateCategoryPreview(categoryId, label) {
    const letter = document.getElementById('categoryPreviewLetter');
    const img = document.getElementById('categoryPreviewImg');
    if (!letter || !img) return;

    clearTimeout(this._previewTimer);

    const newLetter = categoryId === 'all' ? '✦' : label.charAt(0).toUpperCase();
    const cat = GALLERY_CATEGORIES.find(c => c.id === categoryId);
    const newSrc = cat && cat.cover ? this.toThumbPath(cat.cover) : null;

    const applyUpdate = () => {
      letter.textContent = newLetter;
      if (newSrc) {
        img.src = newSrc;
        img.classList.add('visible');
        letter.style.opacity = '0.05';
      } else {
        letter.style.opacity = '';
        this._previewTimer = setTimeout(() => {
          if (!img.classList.contains('visible')) img.src = '';
        }, 350);
      }
    };

    if (img.classList.contains('visible')) {
      img.classList.remove('visible');
      this._previewTimer = setTimeout(applyUpdate, 200);
    } else {
      applyUpdate();
    }
  }
  openCategoryIndex() {
    const index = document.getElementById('categoryIndex');
    if (!index || this.indexOpen) return;
    this.indexOpen = true;
    index.style.pointerEvents = 'all';

    const rows = index.querySelectorAll('.category-row');
    const footer = index.querySelector('.category-index-footer');
    const preview = index.querySelector('.category-preview');
    const closeBtn = index.querySelector('.category-index-close');

    gsap.set(rows, { y: 30, opacity: 0 });
    gsap.set(footer, { y: 15, opacity: 0 });
    gsap.set(preview, { opacity: 0 });
    if (closeBtn) gsap.set(closeBtn, { opacity: 0, rotate: -90 });

    const tl = gsap.timeline();
    tl.to(['.header', '.footer'], { opacity: 0, duration: 0.25, ease: 'power2.in' }, 0);
    tl.to(index, { opacity: 1, duration: 0.35, ease: 'power2.out' }, 0.1);
    tl.to(rows, { y: 0, opacity: 1, duration: 0.5, ease: this.customEase, stagger: 0.035 }, 0.15);
    tl.to(preview, { opacity: 1, duration: 0.5, ease: 'power2.out' }, 0.2);
    tl.to(footer, { y: 0, opacity: 1, duration: 0.35, ease: 'power2.out' }, 0.4);
    if (closeBtn) tl.to(closeBtn, { opacity: 1, rotate: 0, duration: 0.3, ease: 'power2.out' }, 0.3);
  }
  closeCategoryIndex() {
    const index = document.getElementById('categoryIndex');
    if (!index || !this.indexOpen) return;
    const rows = index.querySelectorAll('.category-row');
    const footer = index.querySelector('.category-index-footer');

    const tl = gsap.timeline({
      onComplete: () => {
        this.indexOpen = false;
        index.style.pointerEvents = 'none';
        gsap.set(index, { opacity: 0 });
        const btn = document.getElementById('hamburgerBtn');
        if (btn) btn.classList.remove('open');
        // Reset any open panel
        document.querySelectorAll('.index-panel.active').forEach(p => p.classList.remove('active'));
        document.querySelectorAll('.category-index-nav a').forEach(a => a.classList.remove('panel-active'));
        const scrollBtn = document.getElementById('panelScrollTop');
        if (scrollBtn) scrollBtn.classList.remove('visible');
        this._unbindPanelScroll();
        const catList = document.getElementById('categoryList');
        const preview = document.getElementById('categoryPreview');
        if (catList) { catList.style.display = ''; gsap.set(catList, { opacity: 1, x: 0 }); }
        if (preview) { preview.style.display = ''; gsap.set(preview, { opacity: 1, x: 0 }); }
        this._activePanel = null;
      }
    });
    tl.to(footer, { y: -10, opacity: 0, duration: 0.2, ease: 'power2.in' }, 0);
    tl.to(rows, { y: -20, opacity: 0, duration: 0.25, ease: 'power2.in', stagger: { each: 0.02, from: 'end' } }, 0);
    tl.to(index, { opacity: 0, duration: 0.3, ease: 'power2.in' }, 0.15);
    tl.to(['.header', '.footer'], { opacity: 1, duration: 0.4, ease: 'power2.out' }, 0.35);
  }

  /* ---- Show inline About / Contact panel ---- */
  showIndexPanel(panelName) {
    const catList = document.getElementById('categoryList');
    const preview = document.getElementById('categoryPreview');
    const panel = document.getElementById(panelName === 'about' ? 'indexPanelAbout' : 'indexPanelContact');
    if (!panel) return;

    // If same panel is already open, toggle back to categories
    if (this._activePanel === panelName) {
      this.hideIndexPanel();
      return;
    }

    // Highlight active nav link
    document.querySelectorAll('.category-index-nav a').forEach(a => a.classList.remove('panel-active'));
    const navLink = document.querySelector(`.category-index-nav a[data-panel="${panelName}"]`);
    if (navLink) navLink.classList.add('panel-active');

    const alreadyHasPanel = document.querySelector('.index-panel.active');

    if (alreadyHasPanel) {
      // Switch between panels (About ↔ Contact)
      const scrollBtn = document.getElementById('panelScrollTop');
      if (scrollBtn) scrollBtn.classList.remove('visible');
      gsap.to(alreadyHasPanel, {
        opacity: 0, x: 30, duration: 0.2, ease: 'power2.in',
        onComplete: () => {
          alreadyHasPanel.classList.remove('active');
          panel.classList.add('active');
          panel.scrollTop = 0;
          this._bindPanelScroll(panel);
          gsap.set(panel, { opacity: 0, x: -30 });
          gsap.to(panel, { opacity: 1, x: 0, duration: 0.35, ease: 'power2.out' });
        }
      });
    } else {
      // First open: animate out category list + preview, then show panel
      const tl = gsap.timeline();
      tl.to([catList, preview], {
        opacity: 0, x: -30, duration: 0.3, ease: 'power2.in',
        onComplete: () => {
          catList.style.display = 'none';
          preview.style.display = 'none';
          panel.classList.add('active');
          panel.scrollTop = 0;
          this._bindPanelScroll(panel);
          gsap.set(panel, { opacity: 0, x: 30 });
          gsap.to(panel, { opacity: 1, x: 0, duration: 0.4, ease: 'power2.out' });
        }
      });
    }

    this._activePanel = panelName;
  }

  hideIndexPanel() {
    const catList = document.getElementById('categoryList');
    const preview = document.getElementById('categoryPreview');
    const activePanel = document.querySelector('.index-panel.active');

    // Clear nav highlight & hide back-to-top
    document.querySelectorAll('.category-index-nav a').forEach(a => a.classList.remove('panel-active'));
    const scrollBtn = document.getElementById('panelScrollTop');
    if (scrollBtn) scrollBtn.classList.remove('visible');
    this._unbindPanelScroll();

    if (activePanel) {
      const tl = gsap.timeline();
      tl.to(activePanel, {
        opacity: 0, x: 30, duration: 0.25, ease: 'power2.in',
        onComplete: () => {
          activePanel.classList.remove('active');
          catList.style.display = '';
          preview.style.display = '';
          gsap.set([catList, preview], { opacity: 0, x: -30 });
          gsap.to([catList, preview], { opacity: 1, x: 0, duration: 0.4, ease: 'power2.out' });
        }
      });
    } else {
      catList.style.display = '';
      preview.style.display = '';
    }

    this._activePanel = null;
  }

  /* ---- Panel scroll tracking (back-to-top visibility) ---- */
  _bindPanelScroll(panel) {
    this._unbindPanelScroll();
    const scrollBtn = document.getElementById('panelScrollTop');

    this._panelScrollHandler = () => {
      if (scrollBtn) {
        if (panel.scrollTop > 120) {
          scrollBtn.classList.add('visible');
        } else {
          scrollBtn.classList.remove('visible');
        }
      }
    };
    panel.addEventListener('scroll', this._panelScrollHandler, { passive: true });
    this._panelScrollTarget = panel;
  }

  _unbindPanelScroll() {
    if (this._panelScrollHandler && this._panelScrollTarget) {
      this._panelScrollTarget.removeEventListener('scroll', this._panelScrollHandler);
    }
    this._panelScrollHandler = null;
    this._panelScrollTarget = null;
  }

  switchCategory(categoryId) {
    if (categoryId === this.activeCategory) return;
    if (this.zoomState.isActive) this.exitZoomMode();
    this.activeCategory = categoryId;

    // Update active highlight in the index
    document.querySelectorAll('.category-row').forEach(row => {
      row.classList.toggle('category-row-active', row.dataset.category === categoryId);
    });

    // Resolve images for the category
    if (categoryId === 'all') {
      const allImg = [];
      shuffleArray(GALLERY_CATEGORIES).forEach(c => allImg.push(...c.images));
      this.fashionImages = allImg.length > 0 ? allImg : this.placeholderImages;
    } else {
      const cat = GALLERY_CATEGORIES.find(c => c.id === categoryId);
      this.fashionImages = (cat && cat.images.length) ? cat.images : this.placeholderImages;
    }

    // Adapt grid proportions to image count and screen orientation
    this.setGridShape();

    // Update header label
    const label = document.getElementById('activeCategoryLabel');
    if (label) {
      const cat = GALLERY_CATEGORIES.find(c => c.id === categoryId);
      label.textContent = categoryId === 'all' ? (window.t ? window.t('allWork') : 'All Work') : (window.currentLang === 'ro' && cat.labelRo ? cat.labelRo : cat.label);
    }

    this.transitionGrid();
  }
  transitionGrid() {
    const elements = this.gridItems.map(i => i.element);
    gsap.to(elements, {
      opacity: 0, scale: 0.85, duration: 0.3,
      stagger: { amount: 0.15, from: 'random' },
      onComplete: () => {
        // Auto-fit zoom for the new grid dimensions
        const fitZoom = this.calculateFitZoom();
        this.config.currentZoom = fitZoom;
        this.config.currentGap = this.calculateGapForZoom(fitZoom);
        this.generateGridItems();
        gsap.set(this.canvasWrapper, { scale: fitZoom });
        this.calculateGridDimensions(this.config.currentGap);
        const vw = window.innerWidth;
        const vh = window.innerHeight;
        const { scaledWidth, scaledHeight } = this.gridDimensions;
        const cx = (vw - scaledWidth) / 2;
        const cy = (vh - scaledHeight) / 2;
        gsap.set(this.canvasWrapper, { x: cx, y: cy });
        this.lastValidPosition.x = cx;
        this.lastValidPosition.y = cy;
        this.playIntroAnimation();
        this.initDraggable();
        // Update zoom UI to reflect the new fit zoom
        this.updatePercentageIndicator(fitZoom);
      }
    });
  }
  // --- Scroll-wheel zoom (desktop only) ---
  initScrollZoom() {
    this._scrollZoomDebounce = null;
    this._scrollZoomTween = null;
    this._targetZoom = this.config.currentZoom;
    this._targetX = this.lastValidPosition.x;
    this._targetY = this.lastValidPosition.y;

    this.viewport.addEventListener("wheel", (e) => {
      // Skip when in split-screen zoom mode or on mobile
      if (this.zoomState.isActive || this.isMobile || this._isAnimating) return;
      e.preventDefault();

      const fitZoom = this.calculateFitZoom();
      const minZoom = fitZoom;
      const maxZoom = 1.0;
      const zoomSpeed = 0.001;

      const oldTargetZoom = this._targetZoom;
      // Scroll-up (negative deltaY) = zoom in
      let newZoom = oldTargetZoom - e.deltaY * zoomSpeed;
      newZoom = Math.max(minZoom, Math.min(maxZoom, newZoom));

      if (newZoom === oldTargetZoom) return;

      this._switchButtons.forEach((btn) => btn.classList.remove("switch-button-current"));

      // Read current animated position via GSAP (avoids forced reflow)
      const currentX = gsap.getProperty(this.canvasWrapper, 'x');
      const currentY = gsap.getProperty(this.canvasWrapper, 'y');
      const currentScale = gsap.getProperty(this.canvasWrapper, 'scaleX');

      // Zoom toward mouse cursor based on where canvas actually is right now
      const ratio = newZoom / currentScale;
      const newX = e.clientX - (e.clientX - currentX) * ratio;
      const newY = e.clientY - (e.clientY - currentY) * ratio;

      this._targetZoom = newZoom;
      this._targetX = newX;
      this._targetY = newY;
      this.config.currentZoom = newZoom;

      // Kill previous tween and start a new animated one toward the target
      if (this._scrollZoomTween) this._scrollZoomTween.kill();

      this._scrollZoomTween = gsap.to(this.canvasWrapper, {
        scale: newZoom,
        x: newX,
        y: newY,
        duration: 0.45,
        ease: "power2.out",
        onUpdate: () => {
          // Use GSAP's own tracked values instead of getComputedStyle (avoids forced reflow)
          const tween = this._scrollZoomTween;
          if (tween) {
            this.lastValidPosition.x = gsap.getProperty(this.canvasWrapper, 'x');
            this.lastValidPosition.y = gsap.getProperty(this.canvasWrapper, 'y');
          }
        },
        onComplete: () => {
          this.lastValidPosition.x = newX;
          this.lastValidPosition.y = newY;
        }
      });

      this.updatePercentageIndicator(newZoom);

      // Debounce the heavier work (gap changes, bounds recalc)
      clearTimeout(this._scrollZoomDebounce);
      this._scrollZoomDebounce = setTimeout(() => {
        this.finalizeScrollZoom(newZoom);
      }, 300);
    }, { passive: false });
  }
  finalizeScrollZoom(zoomLevel) {
    this.calculateGridDimensions(this.config.currentGap);
    this.initDraggable();
  }
  /**
   * Animates grid items and canvas wrapper to a new gap size.
   * No-op if the gap hasn't changed.
   */
  _animateGapTransition(newGap, duration = 1.0) {
    if (newGap === this.config.currentGap) return;
    this.gridItems.forEach((itemData) => {
      const newX = itemData.col * (this.config.itemWidth + newGap);
      const newY = itemData.row * (this.config.itemHeight + newGap);
      itemData.baseX = newX;
      itemData.baseY = newY;
      gsap.to(itemData.element, { duration, left: newX, top: newY, ease: this.customEase });
    });
    const newWidth  = this.config.cols * (this.config.itemWidth  + newGap) - newGap;
    const newHeight = this.config.rows * (this.config.itemHeight + newGap) - newGap;
    gsap.to(this.canvasWrapper, { duration, width: newWidth, height: newHeight, ease: this.customEase });
    this.config.currentGap = newGap;
  }
  /** Pinch-to-zoom for mobile — clamped between fitZoom and 1.0, zooms toward pinch midpoint. */
  initPinchZoom() {
    let startDist = 0;
    let startZoom = this.config.currentZoom;
    let startX = 0, startY = 0;       // canvas position at gesture start
    let startMidX = 0, startMidY = 0; // finger midpoint at gesture start

    const getDistance = (touches) => {
      const dx = touches[0].clientX - touches[1].clientX;
      const dy = touches[0].clientY - touches[1].clientY;
      return Math.sqrt(dx * dx + dy * dy);
    };

    // Capture phase: fires before GSAP's bubble-phase listeners on canvasWrapper,
    // so _pinchJustEnded is true before GSAP's tap detection runs.
    this.viewport.addEventListener('touchstart', (e) => {
      if (e.touches.length === 2) {
        if (this._isAnimating) return;
        this._pinchActive = true;
        this._pinchJustEnded = true;
        clearTimeout(this._pinchEndTimer);
        startDist = getDistance(e.touches);
        startZoom = this.config.currentZoom;
        // Snapshot canvas state so touchmove can zoom relative to this baseline
        startX = this.lastValidPosition.x;
        startY = this.lastValidPosition.y;
        startMidX = (e.touches[0].clientX + e.touches[1].clientX) / 2;
        startMidY = (e.touches[0].clientY + e.touches[1].clientY) / 2;
      }
    }, { capture: true, passive: true });

    this.viewport.addEventListener('touchmove', (e) => {
      if (e.touches.length !== 2 || this.zoomState.isActive || startDist === 0 || this._isAnimating) return;
      e.preventDefault();

      this._switchButtons.forEach((btn) => btn.classList.remove("switch-button-current"));

      const dist = getDistance(e.touches);
      const fitZoom = this.calculateFitZoom();
      let newZoom = Math.max(fitZoom, Math.min(1.0, startZoom * (dist / startDist)));

      // Current midpoint between fingers
      const midX = (e.touches[0].clientX + e.touches[1].clientX) / 2;
      const midY = (e.touches[0].clientY + e.touches[1].clientY) / 2;

      let newX, newY;
      if (newZoom <= fitZoom + 0.005) {
        // At minimum zoom, snap to center so the grid can't drift off-screen
        this.calculateGridDimensions(this.config.currentGap);
        const { scaledWidth, scaledHeight } = this.gridDimensions;
        newX = (window.innerWidth  - scaledWidth)  / 2;
        newY = (window.innerHeight - scaledHeight) / 2;
      } else {
        // Zoom toward the pinch midpoint:
        // find which canvas point was under the start-midpoint, keep it there
        const canvasOriginX = (startMidX - startX) / startZoom;
        const canvasOriginY = (startMidY - startY) / startZoom;
        newX = midX - canvasOriginX * newZoom;
        newY = midY - canvasOriginY * newZoom;
      }

      this.config.currentZoom = newZoom;
      this.lastValidPosition.x = newX;
      this.lastValidPosition.y = newY;
      gsap.set(this.canvasWrapper, { scale: newZoom, x: newX, y: newY });
      this.updatePercentageIndicator(newZoom);
    }, { passive: false });

    this.viewport.addEventListener('touchend', (e) => {
      if (e.touches.length < 2 && startDist > 0) {
        startDist = 0;
        this._pinchJustEnded = true;
        clearTimeout(this._pinchEndTimer);
        e.preventDefault();
        this.finalizeScrollZoom(this.config.currentZoom);
      }
      if (e.touches.length === 0) {
        this._pinchActive = false;
        if (this._pinchJustEnded) {
          e.preventDefault();
          clearTimeout(this._pinchEndTimer);
          this._pinchEndTimer = setTimeout(() => { this._pinchJustEnded = false; }, 400);
        }
      }
    }, { passive: false });
  }
  calculateBounds() {
    const vw = window.innerWidth;
    const vh = window.innerHeight;
    const { scaledWidth, scaledHeight } = this.gridDimensions;
    const marginX = this.config.currentGap * this.config.currentZoom;
    const marginY = this.config.currentGap * this.config.currentZoom;
    let minX, maxX, minY, maxY;
    if (scaledWidth <= vw) {
      const centerX = (vw - scaledWidth) / 2;
      minX = maxX = centerX;
    } else {
      maxX = marginX;
      minX = vw - scaledWidth - marginX;
    }
    if (scaledHeight <= vh) {
      const centerY = (vh - scaledHeight) / 2;
      minY = maxY = centerY;
    } else {
      maxY = marginY;
      minY = vh - scaledHeight - marginY;
    }
    return {
      minX,
      maxX,
      minY,
      maxY
    };
  }
initDraggable() {
  if (this.draggable) {
    this.draggable.kill();
  }
  
  this.calculateGridDimensions(this.config.currentGap);
  this._dragBounds = this.calculateBounds();
  const edgeResistance = 0.15; // fraction of movement allowed past edge
  
  this.draggable = Draggable.create(this.canvasWrapper, {
    type: "x,y",
    dragClickables: true,
    allowNativeTouchScrolling: false,
    zIndexBoost: false,
    minimumMovement: this.isMobile ? 10 : 3,
    liveSnap: {
      x: (value) => {
        const b = this._dragBounds;
        if (value > b.maxX) return b.maxX + (value - b.maxX) * edgeResistance;
        if (value < b.minX) return b.minX + (value - b.minX) * edgeResistance;
        return value;
      },
      y: (value) => {
        const b = this._dragBounds;
        if (value > b.maxY) return b.maxY + (value - b.maxY) * edgeResistance;
        if (value < b.minY) return b.minY + (value - b.minY) * edgeResistance;
        return value;
      }
    },
    onClick: (e) => {
      // GSAP fires onClick only when it was NOT a drag — reliable on mobile
      const item = e.target.closest(".grid-item");
      if (!item || this._pinchJustEnded || this.zoomState.isActive) return;
      const itemData = this.gridItems.find(d => d.element === item);
      if (itemData) {
        this.enterZoomMode(itemData);
      }
    },
    onDragStart: () => {
      this._isDragging = true;
      document.body.classList.add("dragging");
      this.lastValidPosition.x = this.draggable.x;
      this.lastValidPosition.y = this.draggable.y;
    },
    onDrag: () => {
      this.lastValidPosition.x = this.draggable.x;
      this.lastValidPosition.y = this.draggable.y;
    },
    onDragEnd: () => {
      document.body.classList.remove("dragging");
      
      // Smooth snap-back if dragged past bounds
      const b = this._dragBounds;
      const currentX = this.draggable.x;
      const currentY = this.draggable.y;
      const clampedX = Math.max(b.minX, Math.min(b.maxX, currentX));
      const clampedY = Math.max(b.minY, Math.min(b.maxY, currentY));
      
      if (Math.abs(clampedX - currentX) > 0.5 || Math.abs(clampedY - currentY) > 0.5) {
        gsap.to(this.canvasWrapper, {
          x: clampedX,
          y: clampedY,
          duration: 0.5,
          ease: "power3.out",
          onUpdate: () => {
            this.lastValidPosition.x = gsap.getProperty(this.canvasWrapper, "x");
            this.lastValidPosition.y = gsap.getProperty(this.canvasWrapper, "y");
          },
          onComplete: () => {
            this.draggable.update();
          }
        });
      }
      
      // Brief delay so the click handler can check _isDragging
      setTimeout(() => { this._isDragging = false; }, 50);
    }
  })[0];
}
  handleMouseLeave() {
    if (document.body.classList.contains("dragging")) {
      document.body.classList.remove("dragging");
      gsap.to(this.canvasWrapper, {
        duration: 0.6,
        x: this.lastValidPosition.x,
        y: this.lastValidPosition.y,
        ease: "power2.out"
      });
      if (this.draggable) {
        this.draggable.endDrag();
      }
    }
  }
  calculateFitZoom() {
    const vw = window.innerWidth;
    const vh = window.innerHeight;
    const currentGap = this.calculateGapForZoom(1.0);
    const gridWidth =
      this.config.cols * (this.config.itemWidth + currentGap) - currentGap;
    const gridHeight =
      this.config.rows * (this.config.itemHeight + currentGap) - currentGap;
    const zoomToFitWidth = vw / gridWidth;
    const zoomToFitHeight = vh / gridHeight;
    const fitZoom = Math.max(zoomToFitWidth, zoomToFitHeight);
    return Math.max(0.1, Math.min(2.0, fitZoom));
  }
  playIntroAnimation() {
    // Place items at their grid positions, hidden
    this.gridItems.forEach((itemData) => {
      gsap.set(itemData.element, {
        left: itemData.baseX,
        top: itemData.baseY,
        scale: 1,
        zIndex: 1,
        opacity: 0
      });
    });

    // onComplete fires after all items have faded in
    const onIntroComplete = () => {
        // Re-enable viewport observer only after intro animation finishes
        this.setupViewportObserver();
        // Show controls with staggered animation
        const percentageIndicator = this.controlsContainer.querySelector(
          ".percentage-indicator"
        );
        const switchElement = this.controlsContainer.querySelector(".switch");
        gsap.set(this.controlsContainer, {
          opacity: 0
        });
        gsap.set(percentageIndicator, {
          x: "-3em"
        });
        gsap.set(switchElement, {
          y: "2em"
        });
        const navTimeline = gsap.timeline();
        navTimeline.to(
          this.controlsContainer,
          {
            opacity: 1,
            duration: 0.5,
            ease: "power2.out"
          },
          0
        );
        navTimeline.to(
          percentageIndicator,
          {
            x: 0,
            duration: 0.2,
            ease: "power2.out"
          },
          0.25
        );
        navTimeline.to(
          switchElement,
          {
            y: 0,
            duration: 0.2,
            ease: "power2.out"
          },
          0.3
        );
        this.controlsContainer.classList.add("visible");
    };

    // Calculate distance from grid center for each item (0 = center, 1 = edge)
    const rows = this.config.rows;
    const cols = this.config.cols;
    const centerRow = (rows - 1) / 2;
    const centerCol = (cols - 1) / 2;
    const maxDist = Math.sqrt(centerRow * centerRow + centerCol * centerCol) || 1;

    // Pre-compute per-item delay and duration based on distance from center + jitter
    let maxFinish = 0;
    const elements  = [];
    const delays    = [];
    const durations = [];
    this.gridItems.forEach((itemData) => {
      const dist     = Math.sqrt((itemData.row - centerRow) ** 2 + (itemData.col - centerCol) ** 2);
      const normDist = dist / maxDist;
      const delay    = Math.max(0, normDist * 2.0 + (Math.random() - 0.5) * 0.3);
      const dur      = 0.5 + normDist * 0.4 + Math.random() * 0.2;
      elements.push(itemData.element);
      delays.push(delay);
      durations.push(dur);
      if (delay + dur > maxFinish) maxFinish = delay + dur;
    });

    // Single gsap.to with a stagger function — one tween object instead of N timeline entries
    gsap.to(elements, {
      opacity: 1,
      duration: (i) => durations[i],
      ease: "sine.out",
      stagger: (i) => delays[i],
    });
    gsap.delayedCall(maxFinish, onIntroComplete);
  }
  autoFitZoom(buttonElement = null) {
    if (this._isAnimating) return;
    if (this.zoomState.isActive) {
      this.exitZoomMode();
      return;
    }
    this._isAnimating = true;
    if (this.draggable) this.draggable.disable();
    gsap.killTweensOf(this.canvasWrapper);
    const fitZoom = this.calculateFitZoom();
    const newGap = this.calculateGapForZoom(fitZoom);
    // Pan to center at the CURRENT scale first, so the grid moves to middle before zooming out
    this.calculateGridDimensions(this.config.currentGap);
    const vw = window.innerWidth;
    const vh = window.innerHeight;
    const currentScaledWidth = this.gridDimensions.width * this.config.currentZoom;
    const currentScaledHeight = this.gridDimensions.height * this.config.currentZoom;
    const centerX = (vw - currentScaledWidth) / 2;
    const centerY = (vh - currentScaledHeight) / 2;
    gsap.to(this.canvasWrapper, {
      duration: 0.6,
      x: centerX,
      y: centerY,
      ease: this.centerEase,
      onComplete: () => {
        this.config.currentZoom = fitZoom;
        this._targetZoom = fitZoom;
        this._animateGapTransition(newGap, 1.0);
        this.calculateGridDimensions(newGap);
        const finalScaledWidth = this.gridDimensions.width * fitZoom;
        const finalScaledHeight = this.gridDimensions.height * fitZoom;
        const finalCenterX = (vw - finalScaledWidth) / 2;
        const finalCenterY = (vh - finalScaledHeight) / 2;
        gsap.to(this.canvasWrapper, {
          duration: 1.2,
          scale: fitZoom,
          x: finalCenterX,
          y: finalCenterY,
          ease: this.customEase,
          onComplete: () => {
            this.lastValidPosition.x = finalCenterX;
            this.lastValidPosition.y = finalCenterY;
            this.initDraggable();
            this._isAnimating = false;
          }
        });
      }
    });
    this.updatePercentageIndicator(fitZoom);
    this._switchButtons.forEach((btn) => btn.classList.remove("switch-button-current"));
    if (buttonElement) {
      buttonElement.classList.add("switch-button-current");
    }
  }
  updatePercentageIndicator(zoomLevel) {
    const percentage = Math.round(zoomLevel * 100);
    document.getElementById(
      "percentageIndicator"
    ).textContent = `${percentage}%`;
  }
  setZoom(zoomLevel, buttonElement = null) {
    if (this._isAnimating) return;
    if (this.zoomState.isActive) {
      this.exitZoomMode();
      return;
    }
    this._isAnimating = true;
    if (this.draggable) this.draggable.disable();
    gsap.killTweensOf(this.canvasWrapper);
    const newGap = this.calculateGapForZoom(zoomLevel);
    const oldZoom = this.config.currentZoom;
    this.config.currentZoom = zoomLevel;
    this._targetZoom = zoomLevel;
    this.calculateGridDimensions(this.config.currentGap);
    const vw = window.innerWidth;
    const vh = window.innerHeight;
    const currentScaledWidth = this.gridDimensions.width * oldZoom;
    const currentScaledHeight = this.gridDimensions.height * oldZoom;
    const centerX = (vw - currentScaledWidth) / 2;
    const centerY = (vh - currentScaledHeight) / 2;
    gsap.to(this.canvasWrapper, {
      duration: 0.6,
      x: centerX,
      y: centerY,
      ease: this.centerEase,
      onComplete: () => {
        this._animateGapTransition(newGap, 1.2);
        this.calculateGridDimensions(newGap);
        const finalScaledWidth = this.gridDimensions.width * zoomLevel;
        const finalScaledHeight = this.gridDimensions.height * zoomLevel;
        const finalCenterX = (vw - finalScaledWidth) / 2;
        const finalCenterY = (vh - finalScaledHeight) / 2;
        gsap.to(this.canvasWrapper, {
          duration: 1.2,
          scale: zoomLevel,
          x: finalCenterX,
          y: finalCenterY,
          ease: this.customEase,
          onComplete: () => {
            this.lastValidPosition.x = finalCenterX;
            this.lastValidPosition.y = finalCenterY;
            this.calculateGridDimensions(newGap);
            this.initDraggable();
            this._isAnimating = false;
          }
        });
      }
    });
    this.updatePercentageIndicator(zoomLevel);
    this._switchButtons.forEach((btn) => btn.classList.remove("switch-button-current"));
    if (buttonElement) {
      buttonElement.classList.add("switch-button-current");
    }
  }
  init() {
    this.buildCategoryIndex();

    // Sync item dimensions to actual viewport before generating the grid
    this._updateConfigForViewport();
    // Always start at NORMAL zoom (0.5) so the NORMAL button is highlighted
    this.config.currentZoom = CONSTANTS.ZOOM.NORMAL;
    // Set grid shape based on aspect ratio and image count
    this.setGridShape();
    this.config.currentGap = this.calculateGapForZoom(this.config.currentZoom);
    this.generateGridItems();

    // Set initial opacity for viewport to hide the flash
    gsap.set(this.viewport, { opacity: 0 });

    gsap.set(this.canvasWrapper, {
      scale: this.config.currentZoom
    });
    this.calculateGridDimensions(this.config.currentGap);
    const vw = window.innerWidth;
    const vh = window.innerHeight;
    const { scaledWidth, scaledHeight } = this.gridDimensions;
    const centerX = (vw - scaledWidth) / 2;
    const centerY = (vh - scaledHeight) / 2;
    gsap.set(this.canvasWrapper, {
      x: centerX,
      y: centerY
    });
    this.lastValidPosition.x = centerX;
    this.lastValidPosition.y = centerY;
    this.updatePercentageIndicator(this.config.currentZoom);

    // Setup event listeners
    this.setupEventListeners();

    // Fade in viewport, then play animations
    gsap.to(this.viewport, {
      duration: 0.6,
      opacity: 1,
      ease: "power2.inOut",
      onComplete: () => {
        this.playIntroAnimation();

        gsap.to(".header", {
          duration: 1.2,
          opacity: 1,
          ease: "power2.out",
          delay: 0.8
        });

        gsap.to(".footer", {
          duration: 1.4,
          opacity: 1,
          ease: "power2.out",
          delay: 1
        });

        setTimeout(() => {
          this.initDraggable();
          this.setupViewportObserver();
        }, 1500);
      }
    });
  }
  setupEventListeners() {
    // Single delegated click handler for grid items — covers the window before Draggable init
    this.gridContainer.addEventListener("click", (e) => {
      if (this._isDragging || this._pinchJustEnded || this.zoomState.isActive) return;
      const item = e.target.closest(".grid-item");
      if (!item) return;
      const itemData = this.gridItems.find(d => d.element === item);
      if (itemData) this.enterZoomMode(itemData);
    });

    window.addEventListener("resize", () => {
      clearTimeout(this._resizeTimer);
      this._resizeTimer = setTimeout(() => {
        this._handleResize();
        this._checkFooterOverlap();
      }, 150);
    });
    if (!this.isMobile) {
      document.addEventListener("mouseleave", () => this.handleMouseLeave());
      this.viewport.addEventListener("mouseleave", () => this.handleMouseLeave());
    }
    // Category index triggers
    const catLabel = document.getElementById('activeCategoryLabel');
    if (catLabel) catLabel.addEventListener('click', () => this.openCategoryIndex());
    const catClose = document.getElementById('categoryIndexClose');
    if (catClose) catClose.addEventListener('click', () => this.closeCategoryIndex());

    // Click sounds for category index footer nav links (inline panels)
    document.querySelectorAll('.category-index-nav a').forEach(link => {
      link.addEventListener('click', (e) => {
        e.preventDefault();
        const panel = link.dataset.panel;
        if (panel) this.showIndexPanel(panel);
      });
    });

    // Back-to-top button for inline panels
    const scrollTopBtn = document.getElementById('panelScrollTop');
    if (scrollTopBtn) {
      scrollTopBtn.addEventListener('click', (e) => {
        e.preventDefault();
        const activePanel = document.querySelector('.index-panel.active');
        if (activePanel) activePanel.scrollTo({ top: 0, behavior: 'smooth' });
      });
    }

    // Zoom control buttons — zoom sounds already play via setZoom/autoFitZoom

    // Scroll-wheel zoom (desktop) / pinch zoom (mobile)
    if (!this.isMobile) {
      this.initScrollZoom();
    } else {
      this.initPinchZoom();
    }

    // Swipe to navigate photos in zoom mode (touch devices)
    this.initZoomSwipe();
    // Keyboard shortcuts
    document.addEventListener("keydown", (e) => {
      if (e.key === "Escape" && this.indexOpen) { this.closeCategoryIndex(); return; }
      if (this.zoomState.isActive || this.indexOpen) return;
      switch (e.key) {
        case "1":
          this.setZoom(0.5);
          break;
        case "2":
          this.setZoom(1.0);
          break;
        case "f":
        case "F":
          this.autoFitZoom();
          break;
        case "i":
        case "I":
          this.openCategoryIndex();
          break;
      }
    });
  }
}
// Initialize gallery with preloader
let gallery;
document.addEventListener("DOMContentLoaded", () => {
  const preloader = new PreloaderManager();

  // Start initialising the gallery immediately so DOM & layout work
  // happens behind the preloader overlay
  gallery = new FashionGallery();
  gallery.init();
  initMobileMenu();

  // Preload only the thumbnails that are actually visible on screen
  // after the initial centered layout, instead of all full-res images
  const vw = window.innerWidth;
  const vh = window.innerHeight;
  const zoom = gallery.config.currentZoom;
  const ox = gallery.lastValidPosition.x;
  const oy = gallery.lastValidPosition.y;
  const preloadSrcs = gallery.gridItems
    .filter((item) => {
      const sx = ox + item.baseX * zoom;
      const sy = oy + item.baseY * zoom;
      const sw = gallery.config.itemWidth * zoom;
      const sh = gallery.config.itemHeight * zoom;
      return sx + sw > 0 && sx < vw && sy + sh > 0 && sy < vh;
    })
    .map((item) => gallery.toThumbPath(item.imageUrl));
  const preloadPromise = Promise.all(
    preloadSrcs.map(
      (src) =>
        new Promise((resolve) => {
          const img = new Image();
          img.onload = resolve;
          img.onerror = resolve; // don't block on failure
          img.src = src;
        })
    )
  );

  // Minimum animation time so the preloader doesn't flash away
  const minTimePromise = new Promise((resolve) => setTimeout(resolve, 2000));

  // Reveal only when both the first thumbnails AND the minimum time are done
  Promise.all([preloadPromise, minTimePromise]).then(() => {
    preloader.complete();
  });
});

function initMobileMenu() {
  const btn = document.getElementById("hamburgerBtn");
  if (!btn) return;

  // Show button with delay matching header fade-in
  setTimeout(() => {
    btn.classList.add("visible");
  }, 1200);

  btn.addEventListener("click", () => {
    if (gallery && gallery.indexOpen) {
      gallery.closeCategoryIndex();
      btn.classList.remove("open");
    } else if (gallery) {
      gallery.openCategoryIndex();
      btn.classList.add("open");
    }
  });

  // Mobile menu nav links
  document.querySelectorAll('.mobile-menu-link').forEach(link => {
    link.addEventListener('click', (e) => {
      e.preventDefault();
      const panel = link.dataset.panel;
      if (panel && gallery) {
        // Close mobile menu, open category index, then show panel
        const mobileOverlay = document.querySelector('.mobile-menu-overlay');
        if (mobileOverlay) mobileOverlay.classList.remove('active');
        btn.classList.remove('open');
        if (!gallery.indexOpen) {
          gallery.openCategoryIndex();
          btn.classList.add('open');
          // Wait for index to open before showing panel
          setTimeout(() => gallery.showIndexPanel(panel), 500);
        } else {
          gallery.showIndexPanel(panel);
        }
      } else {
        const href = link.getAttribute('href');
        setTimeout(() => { window.location.href = href; }, 300);
      }
    });
  });
}
